fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref:  "1.2.2"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.19.0"
    apt:
      repo: "puppetlabs/apt"
      ref:  "2.1.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "1.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref:  "5.1.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref:  "6.0.1"
    firewall:
      repo: "puppetlabs/firewall"
      ref:  "1.5.0"
    puppetserver_gem:
      repo: "puppetlabs/puppetserver_gem"
      ref:  "0.1.0"
  symlinks:
    puppet: "#{source_dir}"
