fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref:  "1.4.1"
    concat:
      repo: "puppetlabs/concat"
      ref:  "'>= 1.2.2 < 2.0.0'"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.6.0"
    apt:
      repo: "puppetlabs/apt"
      ref:  "2.1.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "1.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref:  "4.6.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref:  "5.0.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref:  "1.5.0"
    puppetserver_gem:
      repo: "puppetlabs/puppetserver_gem"
      ref:  "0.1.0"
  symlinks:
    puppet: "#{source_dir}"
