name 'abstractit-puppet'
version '1.6.7'
author 'Abstract IT'
license 'Apache v2 Licence'
source 'https://github.com/abstractitptyltd/abstractit-puppet'
project_page 'https://github.com/abstractitptyltd/abstractit-puppet'
summary 'Manage Puppet agent, master, modules and hiera with Puppet'
dependency 'puppetlabs/apache', '>=0.10.0'
dependency 'puppetlabs/stdlib', '>=0.0.1'
dependency 'puppetlabs/apt', '>=0.0.1'
dependency 'puppetlabs/postgresql', '>=3.0.0'
dependency 'puppetlabs/puppetdb', '>=3.0.0'
dependency 'puppetlabs/ini_setting', '>=0.1.0'
