name 'pivit-puppet'
version '1.3.2'
summary 'puppet master setup for Pivit'
description "puppet master setup for Pivit"
project_page 'https://bitbucket.org/pivitptyltd/puppet-puppet'
dependency 'puppetlabs/apache', '>=1.0.1'
dependency 'puppetlabs/postgresql', '>=3.0.0'
dependency 'puppetlabs/puppetdb', '>=3.0.0'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/vcsrepo', '>=0.2.0'
