class puppet::profile::master (
  $basemodulepath               = undef,
  $environmentpath              = undef,
  $hieradata_path               = undef,
  $hiera_hierarchy              = undef,
  $autosign                     = false,
  $eyaml_keys                   = false,
  $future_parser                = false,
  $java_ram                     = '2g',
  $hiera_backends               = undef,
  $server_type                  = undef,
  $server_version               = 'installed',
  $hiera_eyaml_version          = 'installed',
  $puppet_version               = 'installed',
  $env_owner                    = 'puppet',
  $puppet_server                = 'puppet',
  $puppet_fqdn                  = $::fqdn,
  $passenger_max_pool_size      = '12',
  $passenger_max_requests       = '0',
  $passenger_pool_idle_time     = '1500',
  $passenger_stat_throttle_rate = '120',
) inherits puppet::profile::agent {
  class { '::puppet::master':
    basemodulepath               => $basemodulepath,
    environmentpath              => $environmentpath,
    hieradata_path               => $hieradata_path,
    hiera_hierarchy              => $hiera_hierarchy,
    autosign                     => $autosign,
    eyaml_keys                   => $eyaml_keys,
    future_parser                => $future_parser,
    java_ram                     => $java_ram,
    hiera_backends               => $hiera_backends,
    server_type                  => $server_type,
    server_version               => $server_version,
    hiera_eyaml_version          => $hiera_eyaml_version,
    puppet_version               => $puppet_version,
    env_owner                    => $env_owner,
    puppet_server                => $puppet_server,
    puppet_fqdn                  => $puppet_fqdn,
    passenger_max_pool_size      => $passenger_max_pool_size,
    passenger_max_requests       => $passenger_max_requests,
    passenger_pool_idle_time     => $passenger_pool_idle_time,
    passenger_stat_throttle_rate => $passenger_stat_throttle_rate,
  }

}
